openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Groups
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: {}

components:
  schemas:
    group:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntity'
        - type: object
          properties:
            tagIds:
              type: array
              items:
                allOf:
                  - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            domain:
              description: The target domain of the group
              type: string
          required:
            - domain
          example:
            type: group
            id: Skm7PvmgOh0
            scopeId: AQ
            createdOn: '2019-09-13T15:16:09.174Z'
            createdBy: AQ
            modifiedOn: '2019-09-13T15:16:09.174Z'
            modifiedBy: AQ
            optlock: 1
            tagIds: [ Skm7PvmgOh0 ]
            name: group-1
            description: An Access Group
            domain: device
    groupCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaNamedEntityCreator'
        - type: object
          properties:
            tagIds:
              type: array
              items:
                allOf:
                  - $ref: '../openapi.yaml#/components/schemas/kapuaId'
            domain:
              description: The target domain of the group
              type: string
          required:
            - domain
          example:
            tagIds: [ Skm7PvmgOh0 ]
            name: group-1
            description: An Access Group
            domain: device
    groupListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/group'
          example:
            type: groupListResult
            limitExceeded: false
            size: 1
            items:
              - type: group
                id: Skm7PvmgOh0
                scopeId: AQ
                createdOn: '2019-09-13T15:16:09.174Z'
                createdBy: AQ
                modifiedOn: '2019-09-13T15:16:09.174Z'
                modifiedBy: AQ
                optlock: 1
                name: group-1
                description: An Access Group
                domain: device

    groupPermission:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaEntity'
        - description: An object that represents the link between an Group and a Permission
          type: object
          properties:
            groupId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
                - description: The ID of the Group
            permission:
              $ref: '../accessInfo/accessInfo.yaml#/components/schemas/permission'
          example:
            type: groupPermission
            id: AQ
            scopeId: AQ
            createdOn: '2019-11-12T14:15:47.000Z'
            createdBy: AQ
            groupId: Ag
            permission:
              domain: broker
              action: connect
              targetScopeId: AQ
              forwardable: false
    groupPermissionCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaEntityCreator'
        - description: An object that contains the informations needed to create an GroupPermission
          type: object
          properties:
            groupId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
                - description: The ID of the Group to which attach the Permission
            permission:
              $ref: '../accessInfo/accessInfo.yaml#/components/schemas/permission'
          required:
            - groupId
            - permission
    groupPermissionListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - description: A container for a list of GroupPermission objects
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/groupPermission'
          example:
            type: groupPermissionListResult
            limitExceeded: false
            size: 1
            items:
              - type: groupPermission
                id: Io4dVUnrBtE
                scopeId: AQ
                createdOn: 2019-09-11T14:14:15.786Z
                createdBy: AQ
                groupId: FPRcCYjzgqs
                permission:
                  domain: broker
                  action: connect
                  forwardable: false
    groupRole:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaEntity'
        - description: An object that represents the link between an Group and a Role
          type: object
          properties:
            groupId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
                - description: The ID of the Group
            roleId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
                - description: The ID of the Role attached to the Group
    groupRoleCreator:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaEntityCreator'
        - description: An object that contains the informations needed to create an GroupRole
          type: object
          properties:
            groupId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
                - description: The ID of the Group to which attach the Permission
            roleId:
              allOf:
                - $ref: '../openapi.yaml#/components/schemas/kapuaId'
                - description: The ID of the Group
          required:
            - groupId
            - roleId
    groupRoleListResult:
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaListResult'
        - description: A container for a list of GroupRole objects
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/groupRole'
