name: Eclipse Kapua Release

on:
  release:
    types: [published]
#  push:
#    branches:
#      - release-1.6.x
#      - release-2.0.x
#      - develop

permissions:
  contents: read

env:
  BUILD_OPTS: ""
  MAVEN_OPTS: "-Xmx4096m"

jobs:
  maven-artifacts:
    name: Publish Maven Artifacts
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - uses: actions/checkout@v5 # Checks out a copy of the repository on the ubuntu-latest machine
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'

      - name: Set up Java and Maven Central credentials
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Maven version
        run: mvn --version

      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache

      - name: Build and publish to Central
        run: mvn -B clean deploy -DskipTests -P javadoc,sing
        env:
          MAVEN_USERNAME: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  docker-containers:
    name: Publish Docker Containers
    needs: maven-artifacts
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - uses: actions/checkout@v5 # Checks out a copy of the repository on the ubuntu-latest machine
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 8
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'

      - name: Set up Java and Maven Central credentials
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache

      - name: Build and Publish Kapua Docker Images
        run: mvn -B clean deploy -DskipTests -f assembly -P docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Result
        run: docker images | sort