name: Kapua CI
on: [ push, pull_request ] # Triggers the workflow on push or pull request events

env:
  BUILD_OPTS: ""
  CONFIG_OVERRIDES: "-Dcommons.db.schema=kapuadb -Dcommons.settings.hotswap=true -Dbroker.host=localhost -Dcrypto.secret.key=kapuaTestsKey!!!"
  MAVEN_OPTS: "-Xmx4096m"
  # Secrets
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    name: Build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Checks out a copy of the repository on the ubuntu-latest machine
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5 # Cache local Maven repository to reuse dependencies
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - run: mvn -v
      - run: mvn -B ${BUILD_OPTS} -DskipTests clean install
  test-brokerAcl:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @brokerAcl" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-tag:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @tag" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-broker:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @broker" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-device:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @device" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-device-management:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @deviceManagement" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-connection:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @connection" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-datastore:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @datastore" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-user:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @user" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-security:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @security" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobs:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobs" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-triggerService:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @triggerService" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-account:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @account" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineStepDefinitions:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineStepDefinitions" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineStartOfflineDevice:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineStartOfflineDevice" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineStartOnlineDevice:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineStartOnlineDevice" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineRestartOfflineDevice:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineRestartOfflineDevice" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineRestartOnlineDevice:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineRestartOnlineDevice" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineRestartOnlineDeviceSecondPart:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineRestartOnlineDeviceSecondPart" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  test-jobEngineServiceStop:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='!org.eclipse.kapua.qa.markers.junit.JUnitTests' -Dcucumber.options="--tags @jobEngineServiceStop" verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  junit-tests:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          retry_on: error
          max_attempts: 3
          command: ./ci-output.sh mvn -B ${BUILD_OPTS} ${CONFIG_OVERRIDES} -Dgroups='org.eclipse.kapua.qa.markers.junit.JUnitTests' verify
      - name: Code coverage results upload
        uses: codecov/codecov-action@v6
  build-javadoc:
    needs: build
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '8'
      - uses: actions/setup-node@v5 # Installs Node and NPM
        with:
          node-version: 16
      - name: Install Swagger CLI # Installs Swagger CLI to bundle OpenAPI files
        run: 'npm install -g @apidevtools/swagger-cli'
      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: ${{ github.run_id }}-${{ github.run_number }}-maven-cache
      - run: mvn -B -DskipTests install javadoc:jar
